# Generated by Django 4.0.7 on 2022-08-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRank',
            fields=[
                ('rank', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('player_id', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=500)),
                ('team', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
