# Generated by Django 4.0.7 on 2023-08-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0004_playerrank_positionalrank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerrank',
            old_name='adp',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='playerrank',
            old_name='adpDelta',
            new_name='priority',
        ),
    ]
