# Generated by Django 4.0.7 on 2022-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerrank',
            name='rank',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
