# Generated by Django 4.0.7 on 2022-08-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0002_alter_playerrank_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrank',
            name='adp',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerrank',
            name='adpDelta',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
