# Generated by Django 4.0.7 on 2022-08-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0003_playerrank_adp_playerrank_adpdelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrank',
            name='positionalRank',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
