# Generated by Django 4.0.7 on 2022-08-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
