# Generated by Django 4.0.7 on 2022-08-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=500, primary_key=b'I01\n', serialize=False)),
                ('height', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=500)),
                ('rotoworld_id', models.CharField(max_length=500)),
                ('weight', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=500)),
                ('team', models.CharField(max_length=100)),
                ('years_exp', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('news_updated', models.CharField(max_length=500)),
                ('birth_date', models.CharField(max_length=500)),
                ('fantasy_data_id', models.CharField(max_length=500)),
                ('sport', models.CharField(max_length=100)),
                ('rotowire_id', models.CharField(max_length=500)),
                ('college', models.CharField(max_length=500)),
                ('injury_start_date', models.CharField(max_length=500)),
                ('injury_notes', models.CharField(max_length=500)),
                ('yahoo_id', models.CharField(max_length=500)),
                ('high_school', models.CharField(max_length=500)),
                ('age', models.CharField(max_length=500)),
                ('sportradar_id', models.CharField(max_length=500)),
                ('active', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
            ],
        ),
    ]
